add_newline = false

[character]
symbol = "🌱 "
[directory]
style = "bold cyan"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold yellow"
format = "[$output]($style)"