[settings]
disable_backends = ["asdf", "vfox"]

[tools]
aws = "latest"
actionlint = "latest"
ecspresso = "latest"
github-cli = "latest"
terraform = "latest"

# [Node.js]
node = "lts"
pnpm = "latest"

# [Go]
go = "latest"
